### ISSUE TITLE
Artnet short name change

### ISSUE THREAD

**Issue by elektroservis** [claudeheintz/LXDMXEthernet_library#5]
solved

**Comment by claudeheintz** [comment]
In order for the library to run on an Atmega328 (Uno) the long and short names are stored in an array that holds the contents sent as a poll reply.  A pointer to this array is accessible with replyData().  However, I just added shortName() and longName() which provide pointers into the poll reply array at the correct indexes to make things easier.  (Also, I added setting the long and short names remotely with an artAddress packet)
