### ISSUE TITLE
ArtPoll and ArtPollReply in Input mode

### ISSUE THREAD

**Issue by mrv96** [claudeheintz/LXDMXEthernet_library#6]
Hi, your library is great and works, but checking the output UDP packets I found that isn't 100% compliant with ArtNet standard.

In DMX to ArtNet mode it doesn't send periodic ArtPoll and doesn't answer to ArtPollReply.

I know that from the point of view of functionality it works also as it is, but could you update the library to make it fully compliant with the standard please?

**Comment by claudeheintz** [comment]
The latest commit adds support for sending ArtPoll messages and a callback for ArtPoll reply messages when they are received.

**Comment by mrv96** [comment]
Thank you very much!

________________________________
Da: Claude Heintz <notifications@github.com>
Inviato: Wednesday, March 25, 2020 3:51:11 PM
A: claudeheintz/LXDMXEthernet_library <LXDMXEthernet_library@noreply.github.com>
Cc: mrv96 <marione96@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [claudeheintz/LXDMXEthernet_library] ArtPoll and ArtPollReply in Input mode (#6)


The latest commit adds support for sending ArtPoll messages and a callback for ArtPoll reply messages when they are received.
